-- MySQL Script generated by MySQL Workbench
-- Fri Sep  7 01:48:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema periodicals
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema periodicals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `periodicals` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `periodicals` ;

-- -----------------------------------------------------
-- Table `periodicals`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`user_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `periodicals`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_role` INT(11) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `FK_role` (`user_role` ASC),
  CONSTRAINT `FK_role`
    FOREIGN KEY (`user_role`)
    REFERENCES `periodicals`.`user_role` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `periodicals`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` BIGINT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `account_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `periodicals`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `periodicals`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`payment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL,
  `amount` BIGINT(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `periodicals`.`periodical_period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`periodical_period` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `period` VARCHAR(45) NOT NULL,
  `term` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `periodicals`.`periodical_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`periodical_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `periodicals`.`periodical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`periodical` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) NOT NULL,
  `periodical_type` INT(11) NOT NULL,
  `periodical_period` INT(11) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_type_idx` (`periodical_type` ASC),
  INDEX `FK_period_idx` (`periodical_period` ASC),
  CONSTRAINT `FK_period`
    FOREIGN KEY (`periodical_period`)
    REFERENCES `periodicals`.`periodical_period` (`id`),
  CONSTRAINT `FK_type`
    FOREIGN KEY (`periodical_type`)
    REFERENCES `periodicals`.`periodical_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `periodicals`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`subscription` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `periodical_id` INT(11) NOT NULL,
  `payment_id` INT(11) NOT NULL,
  `expiration_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `payment_id_UNIQUE` (`payment_id` ASC),
  INDEX `FK_periodicalId` (`periodical_id` ASC),
  INDEX `FK_userId` (`user_id` ASC),
  INDEX `FK_paymentId_idx` (`payment_id` ASC),
  CONSTRAINT `FK_paymentId`
    FOREIGN KEY (`payment_id`)
    REFERENCES `periodicals`.`payment` (`id`),
  CONSTRAINT `FK_periodicalId`
    FOREIGN KEY (`periodical_id`)
    REFERENCES `periodicals`.`periodical` (`id`),
  CONSTRAINT `FK_userId`
    FOREIGN KEY (`user_id`)
    REFERENCES `periodicals`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
